<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <ProjectReference Include="../../samples/Microsoft365WorkContext.Console/Microsoft365WorkContext.Console.csproj" />
  </ItemGroup>
</Project>
